import Footer from '@/components/Footer';
import Homepopular from '@/components/home/Homepopular';
import HomeRecent from '@/components/home/HomeRecent';
import HomeSugestions from '@/components/home/HomeSugestions';
import Preferences from '@/components/Preferences';
import Head from 'next/head';
import Header from '../components/Header';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Para Cuando?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <Navbar />
      </section>
      <section>
        <Header />
      </section>
      <section>
        <Homepopular />
      </section>
      <section>
        <HomeSugestions />
      </section>
      <section>
        <Preferences />
      </section>
      <section>
        <HomeRecent />
      </section>
      <section>
        <Footer />
      </section>
    </>
  );
}
